name: test actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  display:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "echo-test"
        run: echo "display my output"
        shell: bash
  comments:
    runs-on: ubuntu-latest
    steps:
      - name: "comment-test"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
